# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Gaurang Bhatnagar
title: Cyber Security Consultant
#email: Your email (optional)
#phone: Your phone number (optional)
#website: Your website (eg. https://google.com)(optional)

darkmode: true

# Social links
twitter_username: eavesdr0pp3r
github_username:  eavesdr0pp3r
#dribbble_username: jekyll
facebook_username: iamgaurangbhatnagar
#flickr_username: jekyll
instagram_username: gaurang_bh
linkedin_username: iamgaurangbhatnagar
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/index.png
about_content: | # this will include new lines to allow paragraphs
 I'm currently working as a security consultant in one of the consultancy firm based in India. 
 
 Following are the key highlights about me:
 
 - Experienced in attacking and defending enterprise systems and networks.
 - Key focus of my research is to find advanced attacks and vulnerabilities in <mark>web</mark>, <mark>mobile</mark> and <mark>network</mark> services.
 - Usually spend my time by doing self research more into offensive security.
 - Highly engaged and active at assessing the security of various organizations and open source projects.


# Projects Section
# projects_title: Blog Posts 

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Contact Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I'm super approachable and do not hesitate to contact me. You can reach me out on my email id: <mark>gaurang.bhatnagar@yahoo.in</mark> or can reach me on my social media profiles. My DM's are always open. 
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
